Issue71 check ggi rconfig
habitus-eu/HabitusGUI pull request #72
Opened 2023-02-22 13:29 UTC by jhmigueles

Fixes issue #71. When the user loads a GGIR config file, if the file is not a config file (it checks (1) file extension and (2) column names of the data frame), then the app generates a sample config file with create_test_GGIRconfig(), stores it in the homedir and uses this one to keep processing the data. The user is notified of this with a red message.

Checklist before merging:

- [ ] Existing tests still work (check by running the test suite, e.g. from RStudio).
- [ ] Added tests (if you added functionality) or fixed existing test (if you fixed a bug).
- [ ] Updated or expanded the documentation.
- [ ] Updated release notes in `inst/NEWS.Rd` with a user-readable summary. Please, include references to relevant issues or PR discussions.
- [ ] Added your name to the contributors lists in the `DESCRIPTION` and `CITATION.cff` files.

2023-02-27 08:34 UTC, vincentvanhees commented
1. Can you add a check at the start to verify that the file is truly comma separated? If the file is tab or semicolon separated then GGIR will still struggle.

2. "and uses this one to keep processing the data." I have not tested the PR yet, but users should not be forced to use a new config. I do not want the user to think that the app takes care of all their challenges. If the user intends to use a certain config file for a study then I think it is confusing to force them to use our template. For example, if the user aims to reproduce a certain analyses then we cannot just replace the file as that would no longer guarantee the reproducibility. The app needs to inform the user what is wrong with the file and encourage them to fix the problem or to download and use a new template.

2023-03-07 15:00 UTC, vincentvanhees requested changes
Hi Jairo, I have tried to run the app locally, but when I select a random csv file on my computer that is not a config file the app crashes. Further, I have some additional feedback on the code (below).

2023-03-07 15:00 UTC, vincentvanhees commented on inst/NEWS.Rd
> +    \item GGIR config file is not checked when it is loaded
typo? `not` => `now`

2023-03-07 15:00 UTC, vincentvanhees commented on R/modConfigServer.R
> +        PALMSPYconfig_check = params$PALMSPYconfig_check
Do I understand correctly that PALMSpy and palmsplusr config files are not actually checked at the moment?
If they are not checked, then I think this needs to be clarified with a comment otherwise the code reads as if all config files are being checked.

2023-03-07 15:00 UTC, vincentvanhees commented on R/modConfigUI.R
> +           span(h5(htmlOutput(NS(id, "GGIRconfigfile_check")), style="color:red")),
Can you combine GGIRconfigfile_check with the already existing configur_issues red magges?
In that way we have one message for all possible config file issues, which keeps the code compact.

Function `modConfigUI.R` is a generic function that is reused for GGIR, PALMSpy and palmsplusr. So, it would be best to not have rerences to either of these. This is why I refer to `config_issues` and `config_green`.

2023-03-07 15:00 UTC, vincentvanhees commented on R/modConfigServer.R
> +        output$PALMSPYconfig_check <- renderUI({
Function modConfigServer.R is a generic function, so please make do not refer to PALMSpy, GGIR or palmsplusr.
This is essential if we want to keep the function scalable to other tools in the future.
Please use config_issues and config_green object to pass on any error or message you want to sent to the console.

2023-03-07 15:02 UTC, vincentvanhees commented on R/modConfigServer.R
> +        output$PALMSPYconfig_check <- renderUI({
Note that when the use uses PALMSpy, GGIR and/or palmsplusr HabitusGUI uses modConfigServer for each of those tools in parallel. This to avoid having to write a new code for each of them.

2023-03-08 12:28 UTC, jhmigueles commented on inst/NEWS.Rd
> +    \item GGIR config file is not checked when it is loaded
Now app does not crash when a different csv is uploaded.

2023-03-08 13:25 UTC, jhmigueles commented on R/modConfigUI.R
> +           span(h5(htmlOutput(NS(id, "GGIRconfigfile_check")), style="color:red")),
Following your email, I have included a checkFile function that tests that the config file is really a config file (for now only for GGIR config files). References to specific tools have therefore been removed.

2023-03-09 18:01 UTC, jhmigueles commented on R/modConfigServer.R
> +        output$PALMSPYconfig_check <- renderUI({
This is done now. I think the last commits include all your proposed changes. Let me know what you think.

2023-03-15 09:41 UTC, vincentvanhees approved these changes

2023-03-15 09:43 UTC, merged