Issue54 app status
habitus-eu/HabitusGUI pull request #78
Opened 2023-04-21 13:37 UTC by jhmigueles

Fixes #54 => All the parameters selected are now stored in "bookmark.RData" and used if available in the app.

Checklist before merging:

- [ ] Existing tests still work (check by running the test suite, e.g. from RStudio).
- [ ] Added tests (if you added functionality) or fixed existing test (if you fixed a bug).
- [ ] Updated or expanded the documentation.
- [ ] Updated release notes in `inst/NEWS.Rd` with a user-readable summary. Please, include references to relevant issues or PR discussions.
- [ ] Added your name to the contributors lists in the `DESCRIPTION` and `CITATION.cff` files.

2023-05-03 09:35 UTC, vincentvanhees requested changes
Thanks @jhmigueles I have a few additional wishes, which I have listed below. Can you reflect on them and then maybe we can discuss in our meeting tomorrow?

1. As a result of the new functionality it is harder to restart the app, because the user will have to manually delete the bookmark file. Proposal: Add button to each page to restart the app, which deletes the Bookmark file. The name of the button would then be "restart app"? It may be best not to put this button next to the "prev" and "next" button but somewhere else such that the user can not accidentally click it.

2. When I reload the app before selecting file paths, the file path will show the message "Directory selected in previous run (to be used if no directory is displayed above): none" which feels not very informative. Can we add a condition to the UI to only show this message when the directory is not "none" or empty?

3. When I run a GGIR analysis, refresh the browser and click again through to page 4 to re-start the GGIR analysis, I get the error
![image](https://user-images.githubusercontent.com/8362333/235879643-26366579-c9da-4081-bf1d-f1d85e06a466.png).

4. The "Next" button currently does not update the Bookmark file. As a result when going to the page 3 and then back again to page 2, the user can see conflicting paths:
![image](https://user-images.githubusercontent.com/8362333/235877748-f096e608-b480-4e0f-95f2-2362dceb2e03.png). Solution may be to always update the bookmark file when the person goes from page 1 to 2, and from 2 to 3 (see code section `observeEvent(input$page_23, {` which is run when user goes from page 2 to 3).

5. In line with the previous point, it may look nicer if the message "Directory selected in previous run..." is not shown when the file path matches the path selected in the box.

2023-05-03 09:35 UTC, vincentvanhees commented on R/myApp.R
> +      save(values, file = "bookmark.RData")
Do I understand correctly that we need to store this in the working directory because that is the only directory the app will remember after being refreshed?

2023-05-11 10:28 UTC, jhmigueles commented
Update: I am trying to fix the error when running GGIR from HABITUS. I could fix the error that you reported, it was related to the definition of the datadir (the app did not consider the datadir from the previous run of the app). But now I am getting a new error I am trying to fix, the configfile path from previous runs is not identied, I am working on that.

2023-05-11 10:38 UTC, vincentvanhees commented
No problem, take your time. I am not going to work on this branch before you tell me to.

2023-05-31 07:27 UTC, vincentvanhees commented
Hi Jairo,

- I am not able to get it to work. For me the app overwrites config.csv with an empty config.csv file and then gives "Error: no lines available in input" on page 4. For this I am using the template config.csv file and I am storing it in the same directory as where I want the results to be stored. So, it seems like the updating of the config file is not going wrong.

- I noticed that when I do:
  1. Open app, and select path
  2. Click refresh page
  3. Go to page 2
  ![image](https://github.com/habitus-eu/HabitusGUI/assets/8362333/58626ddc-ec9d-41a7-bfa4-4fd4b9f9e039)

Could this double forward slash be a problem?

- I am wondering whether `desiredtz` and `configtz` need to be set to c(). Can we not change this to "" as that would default to local timezone. We then need to tell improve the app code such that it recognises that "" is also a valid timezone name.

- Please also change idloc = 3 to idloc = 1 as default in this branch.

- Would it be possible to give me access to https://github.com/jhmigueles/HabitusGUI or did you already add me? Maybe it helps if I also have access to your repo and can make branches?

2023-06-08 10:51 UTC, jhmigueles commented
Now I understand the source of the issue, the app works only if the config file loaded in page 3 is not inside the output directory selected in page 2. I used to work in that way, that's why I did not observe the error that you get, but when loading a config file located inside the output directory, then I get the config overwritten by an empty file (same as you). I'm going to try to fix this now.

2023-06-30 19:18 UTC, vincentvanhees approved these changes
Looks good now, I will merge this PR

2023-06-30 19:18 UTC, merged